// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: todoservice/v1/todo.proto

package todoservicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTODORequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *CreateTODORequest) Reset() {
	*x = CreateTODORequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todoservice_v1_todo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTODORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTODORequest) ProtoMessage() {}

func (x *CreateTODORequest) ProtoReflect() protoreflect.Message {
	mi := &file_todoservice_v1_todo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTODORequest.ProtoReflect.Descriptor instead.
func (*CreateTODORequest) Descriptor() ([]byte, []int) {
	return file_todoservice_v1_todo_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTODORequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateTODOResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateTODOResponse) Reset() {
	*x = CreateTODOResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todoservice_v1_todo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTODOResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTODOResponse) ProtoMessage() {}

func (x *CreateTODOResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todoservice_v1_todo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTODOResponse.ProtoReflect.Descriptor instead.
func (*CreateTODOResponse) Descriptor() ([]byte, []int) {
	return file_todoservice_v1_todo_proto_rawDescGZIP(), []int{1}
}

type ListTODOsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListTODOsRequest) Reset() {
	*x = ListTODOsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todoservice_v1_todo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTODOsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTODOsRequest) ProtoMessage() {}

func (x *ListTODOsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todoservice_v1_todo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTODOsRequest.ProtoReflect.Descriptor instead.
func (*ListTODOsRequest) Descriptor() ([]byte, []int) {
	return file_todoservice_v1_todo_proto_rawDescGZIP(), []int{2}
}

type ListTODOsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Todos []*TODO `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
}

func (x *ListTODOsResponse) Reset() {
	*x = ListTODOsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todoservice_v1_todo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTODOsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTODOsResponse) ProtoMessage() {}

func (x *ListTODOsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todoservice_v1_todo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTODOsResponse.ProtoReflect.Descriptor instead.
func (*ListTODOsResponse) Descriptor() ([]byte, []int) {
	return file_todoservice_v1_todo_proto_rawDescGZIP(), []int{3}
}

func (x *ListTODOsResponse) GetTodos() []*TODO {
	if x != nil {
		return x.Todos
	}
	return nil
}

type UpdateTODORequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *UpdateTODORequest) Reset() {
	*x = UpdateTODORequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todoservice_v1_todo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTODORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTODORequest) ProtoMessage() {}

func (x *UpdateTODORequest) ProtoReflect() protoreflect.Message {
	mi := &file_todoservice_v1_todo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTODORequest.ProtoReflect.Descriptor instead.
func (*UpdateTODORequest) Descriptor() ([]byte, []int) {
	return file_todoservice_v1_todo_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTODORequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTODORequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UpdateTODOResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTODOResponse) Reset() {
	*x = UpdateTODOResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todoservice_v1_todo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTODOResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTODOResponse) ProtoMessage() {}

func (x *UpdateTODOResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todoservice_v1_todo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTODOResponse.ProtoReflect.Descriptor instead.
func (*UpdateTODOResponse) Descriptor() ([]byte, []int) {
	return file_todoservice_v1_todo_proto_rawDescGZIP(), []int{5}
}

type DeleteTODORequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteTODORequest) Reset() {
	*x = DeleteTODORequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todoservice_v1_todo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTODORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTODORequest) ProtoMessage() {}

func (x *DeleteTODORequest) ProtoReflect() protoreflect.Message {
	mi := &file_todoservice_v1_todo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTODORequest.ProtoReflect.Descriptor instead.
func (*DeleteTODORequest) Descriptor() ([]byte, []int) {
	return file_todoservice_v1_todo_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTODORequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTODOResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTODOResponse) Reset() {
	*x = DeleteTODOResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todoservice_v1_todo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTODOResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTODOResponse) ProtoMessage() {}

func (x *DeleteTODOResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todoservice_v1_todo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTODOResponse.ProtoReflect.Descriptor instead.
func (*DeleteTODOResponse) Descriptor() ([]byte, []int) {
	return file_todoservice_v1_todo_proto_rawDescGZIP(), []int{7}
}

type TODO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *TODO) Reset() {
	*x = TODO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todoservice_v1_todo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TODO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TODO) ProtoMessage() {}

func (x *TODO) ProtoReflect() protoreflect.Message {
	mi := &file_todoservice_v1_todo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TODO.ProtoReflect.Descriptor instead.
func (*TODO) Descriptor() ([]byte, []int) {
	return file_todoservice_v1_todo_proto_rawDescGZIP(), []int{8}
}

func (x *TODO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TODO) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_todoservice_v1_todo_proto protoreflect.FileDescriptor

var file_todoservice_v1_todo_proto_rawDesc = []byte{
	0x0a, 0x19, 0x74, 0x6f, 0x64, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x74, 0x6f, 0x64,
	0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x29, 0x0a, 0x11, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x4f, 0x44, 0x4f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x4f, 0x44, 0x4f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x12, 0x0a, 0x10,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x4f, 0x44, 0x4f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x3f, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x4f, 0x44, 0x4f, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x74, 0x6f, 0x64, 0x6f, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x4f, 0x44, 0x4f, 0x52, 0x05, 0x74, 0x6f, 0x64, 0x6f,
	0x73, 0x22, 0x39, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x4f, 0x44, 0x4f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x14, 0x0a, 0x12,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x4f, 0x44, 0x4f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x4f, 0x44, 0x4f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x54, 0x4f, 0x44, 0x4f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2c, 0x0a,
	0x04, 0x54, 0x4f, 0x44, 0x4f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x32, 0xe6, 0x02, 0x0a, 0x0b,
	0x54, 0x4f, 0x44, 0x4f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x0a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x4f, 0x44, 0x4f, 0x12, 0x21, 0x2e, 0x74, 0x6f, 0x64, 0x6f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x4f, 0x44, 0x4f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x74,
	0x6f, 0x64, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x4f, 0x44, 0x4f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x52, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x4f, 0x44, 0x4f, 0x73, 0x12,
	0x20, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x4f, 0x44, 0x4f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x21, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x4f, 0x44, 0x4f, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x4f, 0x44, 0x4f, 0x12, 0x21, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x4f, 0x44, 0x4f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x4f, 0x44, 0x4f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a,
	0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x4f, 0x44, 0x4f, 0x12, 0x21, 0x2e, 0x74, 0x6f,
	0x64, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x4f, 0x44, 0x4f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x4f, 0x44, 0x4f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0xd4, 0x01, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x6f, 0x64,
	0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x09, 0x54, 0x6f, 0x64,
	0x6f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x5a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x4b, 0x69, 0x6d, 0x6f, 0x74, 0x6f, 0x2d, 0x4e, 0x6f, 0x72, 0x69, 0x68, 0x69, 0x72, 0x6f, 0x2f,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2d, 0x74, 0x6f, 0x64, 0x6f, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x6f, 0x64, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x54, 0x58, 0x58, 0xaa, 0x02, 0x0e, 0x54, 0x6f, 0x64,
	0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0e, 0x54, 0x6f,
	0x64, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1a, 0x54,
	0x6f, 0x64, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50,
	0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0f, 0x54, 0x6f, 0x64, 0x6f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_todoservice_v1_todo_proto_rawDescOnce sync.Once
	file_todoservice_v1_todo_proto_rawDescData = file_todoservice_v1_todo_proto_rawDesc
)

func file_todoservice_v1_todo_proto_rawDescGZIP() []byte {
	file_todoservice_v1_todo_proto_rawDescOnce.Do(func() {
		file_todoservice_v1_todo_proto_rawDescData = protoimpl.X.CompressGZIP(file_todoservice_v1_todo_proto_rawDescData)
	})
	return file_todoservice_v1_todo_proto_rawDescData
}

var file_todoservice_v1_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_todoservice_v1_todo_proto_goTypes = []interface{}{
	(*CreateTODORequest)(nil),  // 0: todoservice.v1.CreateTODORequest
	(*CreateTODOResponse)(nil), // 1: todoservice.v1.CreateTODOResponse
	(*ListTODOsRequest)(nil),   // 2: todoservice.v1.ListTODOsRequest
	(*ListTODOsResponse)(nil),  // 3: todoservice.v1.ListTODOsResponse
	(*UpdateTODORequest)(nil),  // 4: todoservice.v1.UpdateTODORequest
	(*UpdateTODOResponse)(nil), // 5: todoservice.v1.UpdateTODOResponse
	(*DeleteTODORequest)(nil),  // 6: todoservice.v1.DeleteTODORequest
	(*DeleteTODOResponse)(nil), // 7: todoservice.v1.DeleteTODOResponse
	(*TODO)(nil),               // 8: todoservice.v1.TODO
}
var file_todoservice_v1_todo_proto_depIdxs = []int32{
	8, // 0: todoservice.v1.ListTODOsResponse.todos:type_name -> todoservice.v1.TODO
	0, // 1: todoservice.v1.TODOService.CreateTODO:input_type -> todoservice.v1.CreateTODORequest
	2, // 2: todoservice.v1.TODOService.ListTODOs:input_type -> todoservice.v1.ListTODOsRequest
	4, // 3: todoservice.v1.TODOService.UpdateTODO:input_type -> todoservice.v1.UpdateTODORequest
	6, // 4: todoservice.v1.TODOService.DeleteTODO:input_type -> todoservice.v1.DeleteTODORequest
	1, // 5: todoservice.v1.TODOService.CreateTODO:output_type -> todoservice.v1.CreateTODOResponse
	3, // 6: todoservice.v1.TODOService.ListTODOs:output_type -> todoservice.v1.ListTODOsResponse
	5, // 7: todoservice.v1.TODOService.UpdateTODO:output_type -> todoservice.v1.UpdateTODOResponse
	7, // 8: todoservice.v1.TODOService.DeleteTODO:output_type -> todoservice.v1.DeleteTODOResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_todoservice_v1_todo_proto_init() }
func file_todoservice_v1_todo_proto_init() {
	if File_todoservice_v1_todo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_todoservice_v1_todo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTODORequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todoservice_v1_todo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTODOResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todoservice_v1_todo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTODOsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todoservice_v1_todo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTODOsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todoservice_v1_todo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTODORequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todoservice_v1_todo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTODOResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todoservice_v1_todo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTODORequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todoservice_v1_todo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTODOResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todoservice_v1_todo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TODO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_todoservice_v1_todo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todoservice_v1_todo_proto_goTypes,
		DependencyIndexes: file_todoservice_v1_todo_proto_depIdxs,
		MessageInfos:      file_todoservice_v1_todo_proto_msgTypes,
	}.Build()
	File_todoservice_v1_todo_proto = out.File
	file_todoservice_v1_todo_proto_rawDesc = nil
	file_todoservice_v1_todo_proto_goTypes = nil
	file_todoservice_v1_todo_proto_depIdxs = nil
}
