// @generated by protoc-gen-connect-web v0.11.0 with parameter "target=ts"
// @generated from file todoservice/v1/todo.proto (package todoservice.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateTODORequest, CreateTODOResponse, DeleteTODORequest, DeleteTODOResponse, ListTODOsRequest, ListTODOsResponse, UpdateTODORequest, UpdateTODOResponse } from "./todo_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service todoservice.v1.TODOService
 */
export const TODOService = {
  typeName: "todoservice.v1.TODOService",
  methods: {
    /**
     * @generated from rpc todoservice.v1.TODOService.CreateTODO
     */
    createTODO: {
      name: "CreateTODO",
      I: CreateTODORequest,
      O: CreateTODOResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc todoservice.v1.TODOService.ListTODOs
     */
    listTODOs: {
      name: "ListTODOs",
      I: ListTODOsRequest,
      O: ListTODOsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc todoservice.v1.TODOService.UpdateTODO
     */
    updateTODO: {
      name: "UpdateTODO",
      I: UpdateTODORequest,
      O: UpdateTODOResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc todoservice.v1.TODOService.DeleteTODO
     */
    deleteTODO: {
      name: "DeleteTODO",
      I: DeleteTODORequest,
      O: DeleteTODOResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

